language: node_js
sudo: false
node_js:
  - 6

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm install coveralls
  - npm run release
  - npm run coveralls
  - npm run gh-pages

deploy:
  - provider: pages
    local_dir: gh-pages
    skip_cleanup: true
    github_token:
      secure: Q2Jwu4mA4X5xLkwk8Ojai2+Pn2MZ0ET4bj7E/63hr04Z8JRKZWLNS709vztia4MKUw72fj+NJZhSyemMBkgCxEs3vSH1LA6G85OVApfNb3+XRNrCFCpV8gDvtaozSpgzrCqsmuwFnzTBSBNxL2HhTH3ehJAnpMM470TLTOnm3ay8L37Cb+x6ExcITtenRJBINqUpv5FuAn7Fds7kQrVLzgDgUH1jZYNhGzxAjRWEU/I8pATPN0bAHV0vxdgE7ZM794aMbY3AUgZh6KuiIqu/vgYWDULxMXphaGQ7Xvb8fWuFIopEZ+7NA+K1L8QsfpMTLaU8fsonTpAiDxJsqGCnBMyMtQ1bEpEqOPd6POqxFfY8E5dIaMaV0xaGbtnjnYRkmGbfXSWBQOdWpldyS4WcQyqnVK5FiW54yIgZee9JYZ7zM+feeJu3DH7jwFKD7a/Z9DeffQwcJtq5g2eClmesRev8WD3Z7P1lLRdaEYAF68u2BY3J0iDzg30NMqt65HvCZWiGADBrN/JSpntV+k4KO7xpvaJ5/KqcxhkcB5cjk/uz6IRUb6WvtxAEfkTDq4/VJQr/K7lF7zybtPWzw7ILMYZ91PYSz+WrnzVpfv5k+lKlFdPRfeOC8QcVTHno1DyvnG5sJBRi/+HjPKDUgoPSOqJIxGyadwVpng/FnCmeHOw=
    on:
      branch: master

  - provider: npm
    skip_cleanup: true
    on:
      tags: true
    email: qowera@qq.com
    api_key:
      secure: WbiiPC0m9vf7Hxkd7xeeZmoZ4FaG3hdiSjsMiupwtQxzOo8bJOvaSZr5s/264UaXGw+gWtydY0EEoXfBduUmcYks4Drb6IJqDdjLD1pZo73DtK0txIkKkM+pARtgvID2B/A9CELqbaOBoaJ8vn29voj9Ibi9iMLwZfYWdwsNt18ZLRRyC81k7TdAhuNF2i3jVzm0+zUnh4al1ypXopl12iuaTQtuHBAncvtk5quNKB15dYWJX020Iz8hHV9SoDFaBgU/Tz0ElAb+o0ZW1NxeIryEgOH5UPgNopxrarGy2HeaxR+g4q2OkG6ePgY19Jfx+3fKVOXLSRzHwwAVRjPurBxKNfR2OVhtswg8fOGebQO0ejfHbBebFBP6JTapz11efHOtSZS7YZQdjXspx1E7dIuua/3BvdbJQS3FQWwh0NqpyVJ1/IqXxK6ZLQz5bifJxxg9CxAYhW+h1rq7n0vXeAWkzzQbpsNMY/WkMb9iy3tWzBLo7c4LIwrWM7qtBszc2ksJllNVq++1q3g3RiGB7VQ4iQF2N/aGauca+a4vcdaVOFksbyL7/L86uWzmf5inh3EO4lQVamU7BAjCzMAopJZzLz7fL+kEAXWzqYOwbOMAJZoRZv5dFQ/Pi+a2HCZfol6ERkSSr02XHhd/hfQjJb7Ed3+DFCHwUtcT7eW1NU4=

after_deploy:
  - bash esdoc.sh
