language: node_js
sudo: false
node_js:
  - 12

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn product

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - yarn product

deploy:
  - provider: script
    skip_cleanup: true
    on:
      tags: true
    script:
      - yarn ci:deploy
